version: '3.9'

services:
  sql-server-travgruva:
    container_name: sql-server-travgruva
    hostname: sql-server-travgruva
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 1433:1433
    environment:
      - SA_PASSWORD=Prettyprettygoodpassword!1
      - ACCEPT_EULA=Y
    volumes:
      - sqlvolume:/var/opt/mssql

volumes:
  sqlvolume: {}